### ISSUE TITLE
content_scripts causes syntaxerror

### ISSUE THREAD

**Issue by japrescott** [KangoExtensions/kango#106]
hey kango team.
cool project you are doing. I wanted to check it out and made a very basic extension.
I noticed in chrome, that when the extension has an entry for a content_scripts in the extension_info.json that it creates an error in the console when opening a tab. The content_script is an empty file. If there is no content_script specified, the error isn't shown.
I'd like to help you but since the source is closed, I cant :( If I can provide additional information, please tell me and I will.
Thanks for looking at this issue!
`
Error in script (unknown): Unexpected token u (console.js:12)
SyntaxError: Unexpected token u (console.js:12)
    at Object.parse (native)
    at Object.object.extend.getItem (chrome-extension://..../kango/storage.js:5:165)
    at Object.<anonymous> (chrome-extension://..../kango/storage.js:6:138)
    at Object.exports.array.forEach (chrome-extension://..../kango/utils.js:9:183)
    at Object.object.extend.getItems (chrome-extension://..../kango/storage.js:6:93)
    at Object.exports.func.invoke (chrome-extension://..../kango/utils.js:14:35)
    at invokeModuleMember (chrome-extension://..../kango/invoke.js:3:230)
    at invoke (chrome-extension://..../kango/invoke.js:3:297)
    at Object.InvokeAsyncModule.t [as KangoInvokeAsyncModule_invoke] (chrome-extension://..../kango/invoke_async.js:4:1)
    at Array.<anonymous> (chrome-extension://..../kango/invoke_async.js:5:396)
`

**Comment by akrylysov** [comment]
Hello, please send compiled extension to extensions@kangoextensions.com
