### ISSUE TITLE
console errors when using content_scripts

### ISSUE THREAD

**Issue by japrescott** [KangoExtensions/kango#110]
if I add a content_script to the extensions_info.json, build the extension, reload it in chromium (within the extension settings), go to a tab, click on the extension and then reload the tab, I get lots of very ugly errors in the tab's console as well as in the extension console;
 Error in script (unknown): Unexpected token u
console.js:12 SyntaxError: Unexpected token u
    at Object.parse (native)
    at Object.object.extend.getItem (chrome-extension://lpfpbmcddmomaelgpfpnaknigeemnclk/kango/storage.js:5:165)
    at Object.<anonymous> (chrome-extension://lpfpbmcddmomaelgpfpnaknigeemnclk/kango/storage.js:6:138)
    at Object.exports.array.forEach (chrome-extension://lpfpbmcddmomaelgpfpnaknigeemnclk/kango/utils.js:9:183)
    at Object.object.extend.getItems (chrome-extension://lpfpbmcddmomaelgpfpnaknigeemnclk/kango/storage.js:6:93)
    at Object.exports.func.invoke (chrome-extension://lpfpbmcddmomaelgpfpnaknigeemnclk/kango/utils.js:14:35)
    at invokeModuleMember (chrome-extension://lpfpbmcddmomaelgpfpnaknigeemnclk/kango/invoke.js:3:230)
    at invoke (chrome-extension://lpfpbmcddmomaelgpfpnaknigeemnclk/kango/invoke.js:3:297)
    at Object.InvokeAsyncModule.t [as KangoInvokeAsyncModule_invoke](chrome-extension://lpfpbmcddmomaelgpfpnaknigeemnclk/kango/invoke_async.js:4:1)
    at Array.<anonymous> (chrome-extension://lpfpbmcddmomaelgpfpnaknigeemnclk/kango/invoke_async.js:5:396)

This happens only when there is a content_scripts listed, even when the script added to content_scripts is essentially empty!
// ==UserScript==
// @name bookmarkletContent
// @namespace myspace
// @include http://*
// @include https://*
// ==/UserScript==

And this sadly also happens with all the examples you have provided (when you reload the tab).

Would be great if you could have a look at this! Thanks for your time and your good work!

**Comment by akrylysov** [comment]
Please send us compiled extension.
