### ISSUE TITLE
Build crashed if default_locate is not "en"

### ISSUE THREAD

**Issue by VitalyOrbit** [KangoExtensions/kango#165]
[   INFO] Contact extensions@kangoextensions.com to enable IE support
[   INFO] Running Kango v1.8.0
[   INFO] Building chrome extension...
Traceback (most recent call last):
  File "kango/kango.py", line 18, in <module>
    main()
  File "kango/kango.py", line 10, in main
    CommandLineProcessor().process()
  File "/run/media/local/USB DISK/PROJECTS/CROSS/kango/kango/commands/processor.py", line 55, in process
    args.execute(args)
  File "/run/media/local/USB DISK/PROJECTS/CROSS/kango/kango/commands/build.py", line 230, in execute
    builder.build(project_dir, args, self._builder_cls, self._build_steps)
  File "/run/media/local/USB DISK/PROJECTS/CROSS/kango/kango/commands/build.py", line 144, in build
    self._build_extension(builderClass, project_dir, out_path, cmd_args, build_steps, ignore)
  File "/run/media/local/USB DISK/PROJECTS/CROSS/kango/kango/commands/build.py", line 125, in _build_extension
    certificates_path, cmd_args)
  File "/run/media/local/USB DISK/PROJECTS/CROSS/kango/kango/builders/chrome.py", line 245, in pack
    shutil.move(extension_dst, crx_path)
  File "/usr/lib64/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:

**Comment by VitalyOrbit** [comment]
Found bug.
My locale JSON was correct, but key was  `"__info__description__"` instead of `"__info_description__"` (double dush in the middle).
My failure, but I don't think there should be that exception.
