### ISSUE TITLE
Invalid value for 'content_security_policy'

### ISSUE THREAD

**Issue by xurei** [KangoExtensions/kango#25]
When I try to build my extension or any of the samples, I got this : 
Building chrome extension
Extension Packaging Error

Invalid value for 'content_security_policy'.
sh: 1: /usr/bin/chromium-browser --pack-extension=/home/olivier/git/gweezy-services/Gweezy/addon/kango/framework/samples/ChristmasTree/output/chrome --pack-extension-key=/home/olivier/git/gweezy-services/Gweezy/addon/kango/framework/samples/ChristmasTree/certificates/chrome.pem --no-message-box : not found
"/usr/bin/chromium-browser" --pack-extension="/home/olivier/git/gweezy-services/Gweezy/addon/kango/framework/samples/ChristmasTree/output/chrome" --pack-extension-key="/home/olivier/git/gweezy-services/Gweezy/addon/kango/framework/samples/ChristmasTree/certificates/chrome.pem" --no-message-box
Traceback (most recent call last):
  File "../../kango.py", line 20, in <module>
    main()
  File "../../kango.py", line 12, in main
    CommandLineProcessor().process()
  File "/home/olivier/git/gweezy-services/Gweezy/addon/kango/framework/kango/commands/processor.py", line 23, in process
    args.execute(args)
  File "/home/olivier/git/gweezy-services/Gweezy/addon/kango/framework/kango/commands/build.py", line 230, in execute
    builder.build(project_dir, args, self._build_steps)
  File "/home/olivier/git/gweezy-services/Gweezy/addon/kango/framework/kango/commands/build.py", line 177, in build
    self._build_extension(builderClass, project_dir, out_path, args, build_steps)
  File "/home/olivier/git/gweezy-services/Gweezy/addon/kango/framework/kango/commands/build.py", line 160, in _build_extension
    builder.pack(out_path, extension_out_path, os.path.join(project_src_path, key))
  File "/home/olivier/git/gweezy-services/Gweezy/addon/kango/framework/kango/builders/chrome.py", line 152, in pack
    subprocess.call(cmd.encode(sys.getfilesystemencoding()))
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by akrylysov** [comment]
You should update your Chrome/Chromium to the latest version.
