### ISSUE TITLE
Version 1.3.3, kango.browser.getCookies, cannot call method 'getAll' of undefined

### ISSUE THREAD

**Issue by smartvault-abbott** [KangoExtensions/kango#80]
Cannot call method 'getAll' of undefined
    at Array.<anonymous> (chrome-extension://bmfgbmkceiakohhomagcddagimapkpdo/background/main.js:490:19)
    at Array.<anonymous> (chrome-extension://bmfgbmkceiakohhomagcddagimapkpdo/kango/message_target.js:3:124)
    at Object.kango.EventTarget.dispatchEvent (chrome-extension://bmfgbmkceiakohhomagcddagimapkpdo/kango/base.js:3:272)
    at Object.kango.EventTarget.fireEvent (chrome-extension://bmfgbmkceiakohhomagcddagimapkpdo/kango/base.js:3:502)
    at Object.kango.MessageRouterBase.fireMessageEvent (chrome-extension://bmfgbmkceiakohhomagcddagimapkpdo/kango/messaging.js:2:470)
    at Object.kango.MessageRouter.kango.oop.extend._onMessage (chrome-extension://bmfgbmkceiakohhomagcddagimapkpdo/kango/messaging.js:15:155)
    at Object.<anonymous> (chrome-extension://bmfgbmkceiakohhomagcddagimapkpdo/kango/messaging.js:14:262)
    at chrome-extension://bmfgbmkceiakohhomagcddagimapkpdo/kango/utils.js:7:216
    at Function.target.(anonymous function) (extensions::SafeBuiltins:19:14)
    at Event.dispatchToListener (extensions::event_bindings:386:22) extensions::event_bindings:375
Event.dispatch_ extensions::event_bindings:375
Event.dispatch extensions::event_bindings:392
dispatchOnMessage extensions::messaging:29

**Comment by akrylysov** [comment]
Please use kango.browser.cookies.*

**Comment by smartvault-abbott** [comment]
Using kango.browser.cookies.getCookies yielded a very similar message.  Is this not the correct name?

Cannot call method 'getAll' of undefined
    at Array.<anonymous> (chrome-extension://bnpleppdaihamhdmhbcmidcjhbceljfb/background/main.js:488:19)
    at Array.<anonymous> (chrome-extension://bnpleppdaihamhdmhbcmidcjhbceljfb/kango/message_target.js:3:124)
    at Object.kango.EventTarget.dispatchEvent (chrome-extension://bnpleppdaihamhdmhbcmidcjhbceljfb/kango/base.js:3:272)
    at Object.kango.EventTarget.fireEvent (chrome-extension://bnpleppdaihamhdmhbcmidcjhbceljfb/kango/base.js:3:502)
    at Object.kango.MessageRouterBase.fireMessageEvent (chrome-extension://bnpleppdaihamhdmhbcmidcjhbceljfb/kango/messaging.js:2:470)
    at Object.kango.MessageRouter.kango.oop.extend._onMessage (chrome-extension://bnpleppdaihamhdmhbcmidcjhbceljfb/kango/messaging.js:15:155)
    at Object.<anonymous> (chrome-extension://bnpleppdaihamhdmhbcmidcjhbceljfb/kango/messaging.js:14:262)
    at chrome-extension://bnpleppdaihamhdmhbcmidcjhbceljfb/kango/utils.js:7:216
    at Function.target.(anonymous function) (extensions::SafeBuiltins:19:14)
    at Event.dispatchToListener (extensions::event_bindings:386:22)

**Comment by akrylysov** [comment]
Please use kango.browser.cookies.getCookies, kango.browser.cookies.getCookie and kango.browser.cookies.setCookie.

**Comment by smartvault-abbott** [comment]
Hello Artem,

As I explained, those APIs gave the same result as the previous. I sent a demo plugin to Andrey that exercises the problem.  Please review the plugin and let me know how to proceed.

John Abbott
SmartVault Corporation

Artem Krylysov notifications@github.com wrote:

Please use kango.browser.cookies.getCookies, kango.browser.cookies.getCookie and kango.browser.cookies.setCookie.

**Comment by akrylysov** [comment]
Sorry for this issue, please add

``` javascript
"permissions": {
        "cookies": true
    }
```

to your extension_info.json.
